site:
  title: 'K3k'
  url: /
  start_page: v1.0.1@k3k:en:introduction.adoc
  robots: disallow
content:
  sources:
  - url: https://github.com/rancher/k3k-product-docs
    branches: [main]
    start_paths: [versions/v*]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./k3k-community-style/supplemental-files
runtime:
  fetch: true
asciidoc:
  attributes:
    # page-draft-preview-only: 'true'
    page-pagination: ''
    ss-build-community: 'true'
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
    index_latest_only: true
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>
      start_on_load: true
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml      
    enabled: true
  - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
    enabled: true

output:
  dir: build-community/site